version: '3'
services:
  centrifugo:
      image: centrifugo/centrifugo:v3.0.5
      volumes:
        - ./config/centrifugo.json:/centrifugo/config.json
      command: centrifugo -c /centrifugo/config.json
      ports:
        - 9000:9000
      ulimits:
        nofile:
          soft: 65535
          hard: 65535
  app:
    ports:
      - 8005:8005
    build:
      context: ./centrifugo
    restart: always
    command: python manage.py runserver 0.0.0.0:8005
  